# Generated by Django 2.2 on 2019-10-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(blank=True, max_length=100, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('platform_type', models.CharField(choices=[('wap', 'wap'), ('web', 'web'), ('app', 'app')], max_length=5)),
                ('action', models.TextField(blank=True, null=True)),
                ('add_id', models.CharField(blank=True, max_length=265, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
